basetable:
  type: netcdf
  file: /p/projects/acclimate/data/eora/Eora26-v199.82-2015.nc
  threshold: 0
output:
  type: netcdf
  file: ./output/EORA-2015-CHN-USA.nc
disaggregation:
  subs:
    - type: region
      id: USA
      into: [ US.AL, US.AK, US.AZ, US.AR, US.CA, US.CO, US.CT, US.DE, US.DC, US.FL, US.GA, US.HI, US.ID, US.IL, US.IN, US.IA, US.KS, US.KY, US.LA, US.ME, US.MD, US.MA, US.MI, US.MN, US.MS, US.MO, US.MT, US.NE, US.NV, US.NH, US.NJ, US.NM, US.NY, US.NC, US.ND, US.OH, US.OK, US.OR, US.PA, US.RI, US.SC, US.SD, US.TN, US.TX, US.UT, US.VT, US.VA, US.WA, US.WV, US.WI, US.WY ]
    - type: region
      id: CHN
      into: [ CN.AH, CN.BJ, CN.CQ, CN.FJ, CN.GS, CN.GD, CN.GX, CN.GZ, CN.HA, CN.HB, CN.HL, CN.HE, CN.HU, CN.HN, CN.JS, CN.JX, CN.JL, CN.LN, CN.NM, CN.NX, CN.QH, CN.SA, CN.SD, CN.SH, CN.SX, CN.SC, CN.TJ, CN.XJ, CN.XZ, CN.YN, CN.ZJ ]
  proxies:
    - file: chn_gdp.csv
      columns:
        year:
          type: select
          value: 2015
        id:
          type: subregion
        gdp:
          type: value
      applications:
        - [ _, id, _, _ ]
        - [ _, _, _, id ]
    - file: usa_gdp.csv
      columns:
        year:
          type: select
          value: 2015
        id:
          type: subregion
        gdp:
          type: value
      applications:
        - [ _, id, _, _ ]
        - [ _, _, _, id ]
    - file: state_gdp_naics_2015.csv
      columns:
        sector:
          type: sector
          mapping:
            file: naics_eora_mapping.csv
            foreign_column: BEA_line_code
            native_column: EORA_sector
        region:
          type: subregion
        gdp:
          type: value
      applications:
        - [ sector, region, _, _ ]
        - [ _, _, sector, region ]
